#!/usr/bin/env python3
"""knowledge/*.md からナレッジバンドルJSを生成（全ファイル自動検出）"""
import os, json

KNOWLEDGE_DIR = os.path.join(os.path.dirname(__file__), '..', 'knowledge')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'knowledge-bundle.js')

# 優先ファイル（先頭に配置）
PRIORITY = ['shibu-biography.md', 'minimalism-principles.md', 'video-pattern-analysis.md']

# 全.mdファイルを自動検出
all_files = sorted(f for f in os.listdir(KNOWLEDGE_DIR) if f.endswith('.md'))
ordered = [f for f in PRIORITY if f in all_files] + [f for f in all_files if f not in PRIORITY]

parts = []
for fname in ordered:
    path = os.path.join(KNOWLEDGE_DIR, fname)
    with open(path, 'r', encoding='utf-8') as f:
        parts.append(f.read())

bundle = '\n\n---\n\n'.join(parts)
bundle = bundle.replace('**', '')

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by build-knowledge.py — do not edit\n')
    f.write(f'const SHIBU_KNOWLEDGE = {json.dumps(bundle, ensure_ascii=False)};\n')

print(f'Generated {OUTPUT} ({len(bundle)} bytes, {len(ordered)} files)')
