#!/usr/bin/env python3
"""knowledge/*.md からナレッジバンドルJSを生成"""
import os, json

KNOWLEDGE_DIR = os.path.join(os.path.dirname(__file__), '..', 'knowledge')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'knowledge-bundle.js')

# コアファイル（優先順）
CORE_FILES = [
    'shibu-biography.md',
    'minimalism-principles.md',
    'video-pattern-analysis.md',
    'shibu-business.md',
    'mono-herashi-coaching.md',
    'minimal-life-program.md',
    'shibu-ecosystem.md',
    '30-questions.md',
    'minimalist-life-cost.md',
    'tesla-life-criticism.md',
    'novel-tesla.md',
]

parts = []
for fname in CORE_FILES:
    path = os.path.join(KNOWLEDGE_DIR, fname)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            parts.append(f.read())

bundle = '\n\n---\n\n'.join(parts)

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by build-knowledge.py — do not edit\n')
    f.write(f'const SHIBU_KNOWLEDGE = {json.dumps(bundle, ensure_ascii=False)};\n')

print(f'Generated {OUTPUT} ({len(bundle)} bytes, {len(CORE_FILES)} files)')
